import type { Asset } from '@/lib/types/layers';

/**
 * Pre-built overlay templates for the Assets panel
 */
export const PREBUILT_OVERLAYS: Asset[] = [
  {
    id: 'overlay-cherry-blossoms',
    name: 'Cherry Blossoms',
    type: 'template',
    category: 'overlays',
    thumbnail: '/CherryBlossoms.mp4', // Video thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: 'Beautiful cherry blossom overlay with animated video background - perfect for nature and calm stream aesthetics',
      shapes: [
        // Video background
        {
          id: 'cherry-video',
          type: 'video',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          videoUrl: '/CherryBlossoms.mp4',
          opacity: 0.7,
          loop: true,
          autoplay: true,
        },
        // Overlay frame/border
        {
          id: 'cherry-frame',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'transparent',
          stroke: 'rgba(255, 192, 203, 0.5)', // Pink border
          strokeWidth: 8,
        },
        // Top gradient overlay for text readability
        {
          id: 'cherry-top-gradient',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 300,
          fill: 'linear-gradient(180deg, rgba(0, 0, 0, 0.6) 0%, transparent 100%)',
        },
        // Bottom gradient overlay for text readability
        {
          id: 'cherry-bottom-gradient',
          type: 'rect',
          x: 0,
          y: 780,
          width: 1920,
          height: 300,
          fill: 'linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, transparent 100%)',
        },
        // Decorative title area
        {
          id: 'cherry-title-bg',
          type: 'rect',
          x: 660,
          y: 80,
          width: 600,
          height: 120,
          fill: 'rgba(255, 192, 203, 0.15)',
          stroke: 'rgba(255, 192, 203, 0.6)',
          strokeWidth: 2,
          cornerRadius: 15,
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 20,
        },
        // Stream title text
        {
          id: 'cherry-title',
          type: 'text',
          x: 960,
          y: 140,
          text: 'YOUR STREAM TITLE',
          fontSize: 48,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.8)',
          shadowBlur: 10,
          shadowOffset: { x: 0, y: 2 },
        },
        // Webcam placeholder
        {
          id: 'cherry-webcam-border',
          type: 'rect',
          x: 1420,
          y: 680,
          width: 420,
          height: 320,
          fill: 'rgba(0, 0, 0, 0.3)',
          stroke: 'rgba(255, 192, 203, 0.8)',
          strokeWidth: 4,
          cornerRadius: 20,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 25,
        },
        // Webcam label
        {
          id: 'cherry-webcam-label',
          type: 'text',
          x: 1630,
          y: 840,
          text: 'WEBCAM',
          fontSize: 24,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 255, 255, 0.5)',
          align: 'center',
          verticalAlign: 'middle',
        },
      ],
      layers: [
        {
          id: 'cherry-video',
          name: 'Cherry Blossoms Video',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 0.7,
          blendMode: 'normal',
        },
        {
          id: 'cherry-frame',
          name: 'Border Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-top-gradient',
          name: 'Top Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-bottom-gradient',
          name: 'Bottom Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', 'nature', 'cherry blossoms', 'video', 'aesthetic', 'calm', 'pink'],
      usage: 'A beautiful nature-themed overlay with animated cherry blossoms. Perfect for calm, aesthetic streams. Edit the title text and webcam position to match your layout. Adjust video opacity for desired effect.',
    },
  },
  {
    id: 'overlay-heartfelt-vision',
    name: 'Heartfelt Vision',
    type: 'template',
    category: 'overlays',
    thumbnail: '/HeartfeltVision.glb', // 3D model thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: '3D animated overlay featuring the Heartfelt Vision 3D model - perfect for immersive and modern stream aesthetics',
      shapes: [
        // Background gradient
        {
          id: 'heartfelt-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'linear-gradient(135deg, rgba(20, 20, 40, 0.95) 0%, rgba(40, 20, 60, 0.95) 100%)',
        },
        // 3D Model container (will render when 3D support is added)
        {
          id: 'heartfelt-model',
          type: '3d-model',
          x: 480,
          y: 140,
          width: 960,
          height: 800,
          modelUrl: '/HeartfeltVision.glb',
          scale: 1.0,
          rotation: { x: 0, y: 0, z: 0 },
          autoRotate: true,
          autoRotateSpeed: 0.5,
        },
        // Decorative frame around 3D model area
        {
          id: 'heartfelt-frame',
          type: 'rect',
          x: 460,
          y: 120,
          width: 1000,
          height: 840,
          fill: 'transparent',
          stroke: 'rgba(147, 70, 255, 0.4)',
          strokeWidth: 3,
          cornerRadius: 20,
          shadowColor: 'rgba(147, 70, 255, 0.5)',
          shadowBlur: 30,
        },
        // Corner accent - top left
        {
          id: 'heartfelt-corner-tl',
          type: 'rect',
          x: 450,
          y: 110,
          width: 40,
          height: 40,
          fill: 'rgba(147, 70, 255, 0.6)',
          cornerRadius: 5,
        },
        // Corner accent - top right
        {
          id: 'heartfelt-corner-tr',
          type: 'rect',
          x: 1430,
          y: 110,
          width: 40,
          height: 40,
          fill: 'rgba(147, 70, 255, 0.6)',
          cornerRadius: 5,
        },
        // Corner accent - bottom left
        {
          id: 'heartfelt-corner-bl',
          type: 'rect',
          x: 450,
          y: 930,
          width: 40,
          height: 40,
          fill: 'rgba(147, 70, 255, 0.6)',
          cornerRadius: 5,
        },
        // Corner accent - bottom right
        {
          id: 'heartfelt-corner-br',
          type: 'rect',
          x: 1430,
          y: 930,
          width: 40,
          height: 40,
          fill: 'rgba(147, 70, 255, 0.6)',
          cornerRadius: 5,
        },
        // Title section
        {
          id: 'heartfelt-title-bg',
          type: 'rect',
          x: 60,
          y: 40,
          width: 350,
          height: 80,
          fill: 'rgba(147, 70, 255, 0.2)',
          stroke: 'rgba(147, 70, 255, 0.6)',
          strokeWidth: 2,
          cornerRadius: 12,
          shadowColor: 'rgba(147, 70, 255, 0.3)',
          shadowBlur: 20,
        },
        // Title text
        {
          id: 'heartfelt-title',
          type: 'text',
          x: 235,
          y: 80,
          text: 'STREAM TITLE',
          fontSize: 32,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.8)',
          shadowBlur: 10,
          shadowOffset: { x: 0, y: 2 },
        },
        // Info panel - bottom left
        {
          id: 'heartfelt-info-bg',
          type: 'rect',
          x: 60,
          y: 920,
          width: 300,
          height: 100,
          fill: 'rgba(0, 0, 0, 0.6)',
          stroke: 'rgba(147, 70, 255, 0.5)',
          strokeWidth: 2,
          cornerRadius: 15,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 25,
        },
        // Info label
        {
          id: 'heartfelt-info-label',
          type: 'text',
          x: 210,
          y: 945,
          text: '3D OVERLAY',
          fontSize: 14,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(147, 70, 255, 1)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Info description
        {
          id: 'heartfelt-info-desc',
          type: 'text',
          x: 210,
          y: 975,
          text: 'Heartfelt Vision',
          fontSize: 24,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 8,
        },
        // Webcam area - bottom right
        {
          id: 'heartfelt-webcam-border',
          type: 'rect',
          x: 1540,
          y: 720,
          width: 320,
          height: 300,
          fill: 'rgba(0, 0, 0, 0.4)',
          stroke: 'rgba(147, 70, 255, 0.8)',
          strokeWidth: 3,
          cornerRadius: 20,
          shadowColor: 'rgba(147, 70, 255, 0.6)',
          shadowBlur: 30,
        },
        // Webcam label
        {
          id: 'heartfelt-webcam-label',
          type: 'text',
          x: 1700,
          y: 870,
          text: 'CAM',
          fontSize: 20,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 255, 255, 0.4)',
          align: 'center',
          verticalAlign: 'middle',
        },
      ],
      layers: [
        {
          id: 'heartfelt-bg',
          name: 'Background Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-model',
          name: '3D Model - Heartfelt Vision',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-frame',
          name: 'Model Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-corner-tl',
          name: 'Corner Accent TL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-corner-tr',
          name: 'Corner Accent TR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-corner-bl',
          name: 'Corner Accent BL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-corner-br',
          name: 'Corner Accent BR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-info-bg',
          name: 'Info Panel Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-info-label',
          name: 'Info Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-info-desc',
          name: 'Info Description',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'heartfelt-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', '3d', '3d-model', 'heartfelt', 'modern', 'immersive', 'animated', 'purple'],
      usage: 'A futuristic 3D overlay featuring the Heartfelt Vision model. The 3D model will render when 3D support is enabled. Customize colors, text, and webcam position to match your stream. The model supports auto-rotation for dynamic visual appeal.',
    },
  },
  {
    id: 'overlay-tactical-mp5',
    name: 'Tactical MP5',
    type: 'template',
    category: 'overlays',
    thumbnail: '/Mp5.glb', // 3D model thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: '3D tactical overlay featuring an MP5 weapon model - perfect for FPS gaming streams, tactical shooters, and action-packed content',
      shapes: [
        // Background gradient - dark tactical theme
        {
          id: 'mp5-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'linear-gradient(135deg, rgba(10, 15, 13, 0.95) 0%, rgba(15, 25, 20, 0.95) 100%)',
        },
        // 3D Model container (will render when 3D support is added)
        {
          id: 'mp5-model',
          type: '3d-model',
          x: 480,
          y: 140,
          width: 960,
          height: 800,
          modelUrl: '/Mp5.glb',
          scale: 1.0,
          rotation: { x: 0, y: 0, z: 0 },
          autoRotate: true,
          autoRotateSpeed: 0.8,
        },
        // Decorative frame around 3D model area
        {
          id: 'mp5-frame',
          type: 'rect',
          x: 460,
          y: 120,
          width: 1000,
          height: 840,
          fill: 'transparent',
          stroke: 'rgba(255, 140, 0, 0.5)', // Orange tactical accent
          strokeWidth: 3,
          cornerRadius: 8,
          shadowColor: 'rgba(255, 140, 0, 0.4)',
          shadowBlur: 25,
        },
        // Corner accent - top left
        {
          id: 'mp5-corner-tl',
          type: 'rect',
          x: 450,
          y: 110,
          width: 50,
          height: 50,
          fill: 'transparent',
          stroke: 'rgba(255, 140, 0, 0.8)',
          strokeWidth: 3,
          cornerRadius: 2,
        },
        // Corner accent - top right
        {
          id: 'mp5-corner-tr',
          type: 'rect',
          x: 1420,
          y: 110,
          width: 50,
          height: 50,
          fill: 'transparent',
          stroke: 'rgba(255, 140, 0, 0.8)',
          strokeWidth: 3,
          cornerRadius: 2,
        },
        // Corner accent - bottom left
        {
          id: 'mp5-corner-bl',
          type: 'rect',
          x: 450,
          y: 920,
          width: 50,
          height: 50,
          fill: 'transparent',
          stroke: 'rgba(255, 140, 0, 0.8)',
          strokeWidth: 3,
          cornerRadius: 2,
        },
        // Corner accent - bottom right
        {
          id: 'mp5-corner-br',
          type: 'rect',
          x: 1420,
          y: 920,
          width: 50,
          height: 50,
          fill: 'transparent',
          stroke: 'rgba(255, 140, 0, 0.8)',
          strokeWidth: 3,
          cornerRadius: 2,
        },
        // Title section - top left
        {
          id: 'mp5-title-bg',
          type: 'rect',
          x: 60,
          y: 40,
          width: 380,
          height: 90,
          fill: 'rgba(0, 0, 0, 0.7)',
          stroke: 'rgba(255, 140, 0, 0.6)',
          strokeWidth: 2,
          cornerRadius: 4,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 20,
        },
        // Title text
        {
          id: 'mp5-title',
          type: 'text',
          x: 250,
          y: 85,
          text: 'TACTICAL STREAM',
          fontSize: 36,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff8c00',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.9)',
          shadowBlur: 12,
          shadowOffset: { x: 0, y: 2 },
        },
        // Status bar - top right
        {
          id: 'mp5-status-bg',
          type: 'rect',
          x: 1480,
          y: 40,
          width: 380,
          height: 90,
          fill: 'rgba(0, 0, 0, 0.7)',
          stroke: 'rgba(255, 140, 0, 0.6)',
          strokeWidth: 2,
          cornerRadius: 4,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 20,
        },
        // Status label
        {
          id: 'mp5-status-label',
          type: 'text',
          x: 1670,
          y: 65,
          text: 'LIVE',
          fontSize: 18,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 140, 0, 0.9)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Status value
        {
          id: 'mp5-status-value',
          type: 'text',
          x: 1670,
          y: 95,
          text: 'GAMING',
          fontSize: 28,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.7)',
          shadowBlur: 8,
        },
        // Info panel - bottom left
        {
          id: 'mp5-info-bg',
          type: 'rect',
          x: 60,
          y: 900,
          width: 320,
          height: 120,
          fill: 'rgba(0, 0, 0, 0.7)',
          stroke: 'rgba(255, 140, 0, 0.6)',
          strokeWidth: 2,
          cornerRadius: 4,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 25,
        },
        // Info label
        {
          id: 'mp5-info-label',
          type: 'text',
          x: 220,
          y: 930,
          text: '3D WEAPON OVERLAY',
          fontSize: 12,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 140, 0, 1)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Info description
        {
          id: 'mp5-info-desc',
          type: 'text',
          x: 220,
          y: 965,
          text: 'MP5 Tactical',
          fontSize: 28,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.7)',
          shadowBlur: 10,
        },
        // Ammo counter style element
        {
          id: 'mp5-ammo-label',
          type: 'text',
          x: 220,
          y: 995,
          text: '30 / 120',
          fontSize: 16,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 140, 0, 0.8)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Webcam area - bottom right
        {
          id: 'mp5-webcam-border',
          type: 'rect',
          x: 1520,
          y: 700,
          width: 340,
          height: 320,
          fill: 'rgba(0, 0, 0, 0.5)',
          stroke: 'rgba(255, 140, 0, 0.8)',
          strokeWidth: 3,
          cornerRadius: 8,
          shadowColor: 'rgba(255, 140, 0, 0.5)',
          shadowBlur: 25,
        },
        // Webcam label
        {
          id: 'mp5-webcam-label',
          type: 'text',
          x: 1690,
          y: 860,
          text: 'OPERATOR',
          fontSize: 16,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 140, 0, 0.7)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Crosshair accent
        {
          id: 'mp5-crosshair-h',
          type: 'rect',
          x: 940,
          y: 538,
          width: 40,
          height: 4,
          fill: 'rgba(255, 140, 0, 0.3)',
          cornerRadius: 2,
        },
        // Crosshair accent vertical
        {
          id: 'mp5-crosshair-v',
          type: 'rect',
          x: 958,
          y: 520,
          width: 4,
          height: 40,
          fill: 'rgba(255, 140, 0, 0.3)',
          cornerRadius: 2,
        },
      ],
      layers: [
        {
          id: 'mp5-bg',
          name: 'Background Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-model',
          name: '3D Model - MP5',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-frame',
          name: 'Model Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-corner-tl',
          name: 'Corner Accent TL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-corner-tr',
          name: 'Corner Accent TR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-corner-bl',
          name: 'Corner Accent BL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-corner-br',
          name: 'Corner Accent BR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-status-bg',
          name: 'Status Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-status-label',
          name: 'Status Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-status-value',
          name: 'Status Value',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-info-bg',
          name: 'Info Panel Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-info-label',
          name: 'Info Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-info-desc',
          name: 'Info Description',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-ammo-label',
          name: 'Ammo Counter',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-crosshair-h',
          name: 'Crosshair Horizontal',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'mp5-crosshair-v',
          name: 'Crosshair Vertical',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', '3d', '3d-model', 'weapon', 'mp5', 'gaming', 'fps', 'tactical', 'action', 'shooter', 'orange'],
      usage: 'A tactical gaming overlay featuring a 3D MP5 weapon model. Perfect for FPS streams, tactical shooters, and action-packed gaming content. The 3D model will render when 3D support is enabled. Customize the colors, text, HUD elements, and webcam position to match your gaming brand. Features tactical orange accents and a military aesthetic.',
    },
  },
  {
    id: 'overlay-samurai-kitty',
    name: 'Samurai Kitty',
    type: 'template',
    category: 'overlays',
    thumbnail: '/SamuraiKitty.glb', // 3D model thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: '3D animated overlay featuring an adorable Samurai Kitty character - perfect for gaming, anime, and kawaii aesthetic streams',
      shapes: [
        // Background gradient - cute aesthetic theme
        {
          id: 'samurai-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'linear-gradient(135deg, rgba(255, 182, 193, 0.95) 0%, rgba(255, 218, 224, 0.95) 50%, rgba(230, 230, 250, 0.95) 100%)',
        },
        // 3D Model container (will render when 3D support is added)
        {
          id: 'samurai-model',
          type: '3d-model',
          x: 480,
          y: 140,
          width: 960,
          height: 800,
          modelUrl: '/SamuraiKitty.glb',
          scale: 1.0,
          rotation: { x: 0, y: 0, z: 0 },
          autoRotate: true,
          autoRotateSpeed: 0.6,
        },
        // Decorative frame around 3D model area
        {
          id: 'samurai-frame',
          type: 'rect',
          x: 460,
          y: 120,
          width: 1000,
          height: 840,
          fill: 'transparent',
          stroke: 'rgba(255, 105, 180, 0.5)', // Hot pink accent
          strokeWidth: 4,
          cornerRadius: 25,
          shadowColor: 'rgba(255, 105, 180, 0.4)',
          shadowBlur: 30,
        },
        // Corner accent - top left (cherry blossom style)
        {
          id: 'samurai-corner-tl',
          type: 'circle',
          x: 470,
          y: 130,
          radius: 20,
          fill: 'rgba(255, 182, 193, 0.8)',
          stroke: 'rgba(255, 105, 180, 0.8)',
          strokeWidth: 2,
        },
        // Corner accent - top right
        {
          id: 'samurai-corner-tr',
          type: 'circle',
          x: 1450,
          y: 130,
          radius: 20,
          fill: 'rgba(255, 182, 193, 0.8)',
          stroke: 'rgba(255, 105, 180, 0.8)',
          strokeWidth: 2,
        },
        // Corner accent - bottom left
        {
          id: 'samurai-corner-bl',
          type: 'circle',
          x: 470,
          y: 950,
          radius: 20,
          fill: 'rgba(255, 182, 193, 0.8)',
          stroke: 'rgba(255, 105, 180, 0.8)',
          strokeWidth: 2,
        },
        // Corner accent - bottom right
        {
          id: 'samurai-corner-br',
          type: 'circle',
          x: 1450,
          y: 950,
          radius: 20,
          fill: 'rgba(255, 182, 193, 0.8)',
          stroke: 'rgba(255, 105, 180, 0.8)',
          strokeWidth: 2,
        },
        // Title section
        {
          id: 'samurai-title-bg',
          type: 'rect',
          x: 710,
          y: 40,
          width: 500,
          height: 100,
          fill: 'rgba(255, 255, 255, 0.7)',
          stroke: 'rgba(255, 105, 180, 0.8)',
          strokeWidth: 3,
          cornerRadius: 20,
          shadowColor: 'rgba(255, 105, 180, 0.4)',
          shadowBlur: 25,
        },
        // Title text
        {
          id: 'samurai-title',
          type: 'text',
          x: 960,
          y: 90,
          text: 'KAWAII STREAM',
          fontSize: 42,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff69b4',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 8,
          shadowOffset: { x: 0, y: 2 },
        },
        // Decorative cherry blossom - left side
        {
          id: 'samurai-blossom-left',
          type: 'circle',
          x: 100,
          y: 200,
          radius: 40,
          fill: 'rgba(255, 182, 193, 0.6)',
          shadowColor: 'rgba(255, 105, 180, 0.3)',
          shadowBlur: 20,
        },
        // Decorative cherry blossom - right side
        {
          id: 'samurai-blossom-right',
          type: 'circle',
          x: 1820,
          y: 300,
          radius: 35,
          fill: 'rgba(255, 182, 193, 0.6)',
          shadowColor: 'rgba(255, 105, 180, 0.3)',
          shadowBlur: 20,
        },
        // Info panel - bottom center
        {
          id: 'samurai-info-bg',
          type: 'rect',
          x: 710,
          y: 940,
          width: 500,
          height: 90,
          fill: 'rgba(255, 255, 255, 0.8)',
          stroke: 'rgba(255, 105, 180, 0.7)',
          strokeWidth: 3,
          cornerRadius: 18,
          shadowColor: 'rgba(0, 0, 0, 0.2)',
          shadowBlur: 20,
        },
        // Info label
        {
          id: 'samurai-info-label',
          type: 'text',
          x: 960,
          y: 960,
          text: '🌸 3D CHARACTER 🌸',
          fontSize: 16,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 105, 180, 1)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Info description
        {
          id: 'samurai-info-desc',
          type: 'text',
          x: 960,
          y: 995,
          text: 'Samurai Kitty',
          fontSize: 32,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff69b4',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.2)',
          shadowBlur: 6,
        },
        // Webcam area - bottom left
        {
          id: 'samurai-webcam-border',
          type: 'rect',
          x: 80,
          y: 720,
          width: 340,
          height: 300,
          fill: 'rgba(255, 255, 255, 0.5)',
          stroke: 'rgba(255, 105, 180, 0.9)',
          strokeWidth: 4,
          cornerRadius: 25,
          shadowColor: 'rgba(255, 105, 180, 0.5)',
          shadowBlur: 30,
        },
        // Webcam label
        {
          id: 'samurai-webcam-label',
          type: 'text',
          x: 250,
          y: 870,
          text: 'WEBCAM',
          fontSize: 22,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 105, 180, 0.8)',
          align: 'center',
          verticalAlign: 'middle',
        },
      ],
      layers: [
        {
          id: 'samurai-bg',
          name: 'Background Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-model',
          name: '3D Model - Samurai Kitty',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-frame',
          name: 'Model Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-corner-tl',
          name: 'Corner Accent TL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-corner-tr',
          name: 'Corner Accent TR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-corner-bl',
          name: 'Corner Accent BL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-corner-br',
          name: 'Corner Accent BR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-blossom-left',
          name: 'Cherry Blossom Left',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-blossom-right',
          name: 'Cherry Blossom Right',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-info-bg',
          name: 'Info Panel Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-info-label',
          name: 'Info Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-info-desc',
          name: 'Info Description',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'samurai-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', '3d', '3d-model', 'samurai', 'kitty', 'cat', 'kawaii', 'cute', 'anime', 'gaming', 'pink', 'japanese'],
      usage: 'An adorable kawaii overlay featuring a 3D Samurai Kitty character. Perfect for gaming streams, anime content, and cute aesthetic channels. The 3D model will render when 3D support is enabled. Customize the pink theme, text, and webcam position to match your brand. Features soft pastel gradients and cherry blossom accents for a Japanese-inspired aesthetic.',
    },
  },
  {
    id: 'overlay-kacchan',
    name: 'Kacchan',
    type: 'template',
    category: 'overlays',
    thumbnail: '/kacchan.glb', // 3D model thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: '3D anime character overlay featuring Kacchan - perfect for anime streams, hero-themed content, and explosive gaming action',
      shapes: [
        // Background gradient - explosive hero theme
        {
          id: 'kacchan-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'linear-gradient(135deg, rgba(255, 87, 34, 0.95) 0%, rgba(255, 152, 0, 0.95) 50%, rgba(255, 193, 7, 0.95) 100%)',
        },
        // 3D Model container (will render when 3D support is added)
        {
          id: 'kacchan-model',
          type: '3d-model',
          x: 480,
          y: 140,
          width: 960,
          height: 800,
          modelUrl: '/kacchan.glb',
          scale: 1.0,
          rotation: { x: 0, y: 0, z: 0 },
          autoRotate: true,
          autoRotateSpeed: 0.7,
        },
        // Decorative frame around 3D model area
        {
          id: 'kacchan-frame',
          type: 'rect',
          x: 460,
          y: 120,
          width: 1000,
          height: 840,
          fill: 'transparent',
          stroke: 'rgba(255, 87, 34, 0.6)', // Orange/red accent
          strokeWidth: 4,
          cornerRadius: 15,
          shadowColor: 'rgba(255, 87, 34, 0.5)',
          shadowBlur: 35,
        },
        // Explosive corner accent - top left
        {
          id: 'kacchan-corner-tl',
          type: 'rect',
          x: 445,
          y: 105,
          width: 60,
          height: 60,
          fill: 'rgba(255, 87, 34, 0.3)',
          rotation: 45,
          cornerRadius: 8,
        },
        // Explosive corner accent - top right
        {
          id: 'kacchan-corner-tr',
          type: 'rect',
          x: 1415,
          y: 105,
          width: 60,
          height: 60,
          fill: 'rgba(255, 87, 34, 0.3)',
          rotation: 45,
          cornerRadius: 8,
        },
        // Explosive corner accent - bottom left
        {
          id: 'kacchan-corner-bl',
          type: 'rect',
          x: 445,
          y: 915,
          width: 60,
          height: 60,
          fill: 'rgba(255, 87, 34, 0.3)',
          rotation: 45,
          cornerRadius: 8,
        },
        // Explosive corner accent - bottom right
        {
          id: 'kacchan-corner-br',
          type: 'rect',
          x: 1415,
          y: 915,
          width: 60,
          height: 60,
          fill: 'rgba(255, 87, 34, 0.3)',
          rotation: 45,
          cornerRadius: 8,
        },
        // Title section
        {
          id: 'kacchan-title-bg',
          type: 'rect',
          x: 710,
          y: 40,
          width: 500,
          height: 100,
          fill: 'rgba(0, 0, 0, 0.7)',
          stroke: 'rgba(255, 87, 34, 0.9)',
          strokeWidth: 3,
          cornerRadius: 15,
          shadowColor: 'rgba(255, 87, 34, 0.6)',
          shadowBlur: 30,
        },
        // Title text
        {
          id: 'kacchan-title',
          type: 'text',
          x: 960,
          y: 90,
          text: 'HERO STREAM',
          fontSize: 44,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff5722',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.8)',
          shadowBlur: 12,
          shadowOffset: { x: 0, y: 3 },
        },
        // Explosion accent - left side
        {
          id: 'kacchan-blast-left',
          type: 'circle',
          x: 120,
          y: 250,
          radius: 45,
          fill: 'rgba(255, 152, 0, 0.4)',
          shadowColor: 'rgba(255, 87, 34, 0.5)',
          shadowBlur: 25,
        },
        // Explosion accent - right side
        {
          id: 'kacchan-blast-right',
          type: 'circle',
          x: 1800,
          y: 350,
          radius: 40,
          fill: 'rgba(255, 193, 7, 0.4)',
          shadowColor: 'rgba(255, 87, 34, 0.5)',
          shadowBlur: 25,
        },
        // Power level indicator - top right
        {
          id: 'kacchan-power-bg',
          type: 'rect',
          x: 1520,
          y: 40,
          width: 340,
          height: 100,
          fill: 'rgba(0, 0, 0, 0.8)',
          stroke: 'rgba(255, 87, 34, 0.8)',
          strokeWidth: 3,
          cornerRadius: 15,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 20,
        },
        // Power label
        {
          id: 'kacchan-power-label',
          type: 'text',
          x: 1690,
          y: 65,
          text: 'POWER LEVEL',
          fontSize: 14,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 152, 0, 1)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Power value
        {
          id: 'kacchan-power-value',
          type: 'text',
          x: 1690,
          y: 100,
          text: '∞',
          fontSize: 36,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff5722',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(255, 87, 34, 0.8)',
          shadowBlur: 15,
        },
        // Info panel - bottom center
        {
          id: 'kacchan-info-bg',
          type: 'rect',
          x: 710,
          y: 940,
          width: 500,
          height: 90,
          fill: 'rgba(0, 0, 0, 0.8)',
          stroke: 'rgba(255, 87, 34, 0.8)',
          strokeWidth: 3,
          cornerRadius: 18,
          shadowColor: 'rgba(0, 0, 0, 0.4)',
          shadowBlur: 25,
        },
        // Info label
        {
          id: 'kacchan-info-label',
          type: 'text',
          x: 960,
          y: 960,
          text: '💥 3D HERO 💥',
          fontSize: 16,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 152, 0, 1)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Info description
        {
          id: 'kacchan-info-desc',
          type: 'text',
          x: 960,
          y: 995,
          text: 'Kacchan',
          fontSize: 32,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ff5722',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 8,
        },
        // Webcam area - bottom left
        {
          id: 'kacchan-webcam-border',
          type: 'rect',
          x: 80,
          y: 720,
          width: 340,
          height: 300,
          fill: 'rgba(0, 0, 0, 0.6)',
          stroke: 'rgba(255, 87, 34, 0.9)',
          strokeWidth: 4,
          cornerRadius: 20,
          shadowColor: 'rgba(255, 87, 34, 0.6)',
          shadowBlur: 30,
        },
        // Webcam label
        {
          id: 'kacchan-webcam-label',
          type: 'text',
          x: 250,
          y: 870,
          text: 'CAMERA',
          fontSize: 22,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 152, 0, 0.9)',
          align: 'center',
          verticalAlign: 'middle',
        },
      ],
      layers: [
        {
          id: 'kacchan-bg',
          name: 'Background Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-model',
          name: '3D Model - Kacchan',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-frame',
          name: 'Model Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-corner-tl',
          name: 'Explosive Accent TL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-corner-tr',
          name: 'Explosive Accent TR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-corner-bl',
          name: 'Explosive Accent BL',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-corner-br',
          name: 'Explosive Accent BR',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-blast-left',
          name: 'Explosion Left',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-blast-right',
          name: 'Explosion Right',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-power-bg',
          name: 'Power Level Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-power-label',
          name: 'Power Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-power-value',
          name: 'Power Value',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-info-bg',
          name: 'Info Panel Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-info-label',
          name: 'Info Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-info-desc',
          name: 'Info Description',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'kacchan-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', '3d', '3d-model', 'kacchan', 'anime', 'hero', 'action', 'gaming', 'explosive', 'orange', 'mha', 'character'],
      usage: 'An explosive hero-themed overlay featuring the 3D Kacchan character model. Perfect for anime streams, action-packed gaming, and hero-themed content. The 3D model will render when 3D support is enabled. Customize the fiery orange theme, power levels, text, and webcam position to match your explosive streaming style. Features dynamic gradient backgrounds and hero-inspired UI elements.',
    },
  },
];

/**
 * Pre-built widget templates for the Assets panel
 */
export const PREBUILT_WIDGETS: Asset[] = [
  {
    id: 'widget-alert-box',
    name: 'Alert Box',
    type: 'template',
    category: 'widgets',
    thumbnail: '/assets/widgets/alert-box-thumb.png', // You can update this with actual thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: 'Classic stream alert box for followers, subs, donations, and raids',
      shapes: [
        // Background container
        {
          id: 'alert-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 800,
          height: 300,
          fill: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          stroke: '#ffffff',
          strokeWidth: 4,
          cornerRadius: 20,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 30,
          shadowOffset: { x: 0, y: 10 },
          shadowOpacity: 0.8,
        },
        // Inner glow effect
        {
          id: 'alert-inner-glow',
          type: 'rect',
          x: 8,
          y: 8,
          width: 784,
          height: 284,
          fill: 'transparent',
          stroke: 'rgba(255, 255, 255, 0.3)',
          strokeWidth: 2,
          cornerRadius: 16,
        },
        // Icon/Avatar placeholder circle
        {
          id: 'alert-icon',
          type: 'circle',
          x: 100,
          y: 150,
          radius: 60,
          fill: '#ffffff',
          stroke: '#667eea',
          strokeWidth: 4,
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 15,
        },
        // Alert title text
        {
          id: 'alert-title',
          type: 'text',
          x: 400,
          y: 80,
          text: 'NEW FOLLOWER!',
          fontSize: 48,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 10,
          shadowOffset: { x: 0, y: 4 },
        },
        // Username/message text
        {
          id: 'alert-message',
          type: 'text',
          x: 400,
          y: 150,
          text: 'Username',
          fontSize: 36,
          fontFamily: 'Arial',
          fontStyle: 'normal',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 6,
        },
        // Subtitle/thank you text
        {
          id: 'alert-subtitle',
          type: 'text',
          x: 400,
          y: 220,
          text: 'Thank you for the support!',
          fontSize: 24,
          fontFamily: 'Arial',
          fontStyle: 'italic',
          fill: 'rgba(255, 255, 255, 0.9)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Decorative accent line top
        {
          id: 'alert-accent-top',
          type: 'rect',
          x: 200,
          y: 40,
          width: 400,
          height: 4,
          fill: '#ffffff',
          cornerRadius: 2,
        },
        // Decorative accent line bottom
        {
          id: 'alert-accent-bottom',
          type: 'rect',
          x: 200,
          y: 256,
          width: 400,
          height: 4,
          fill: '#ffffff',
          cornerRadius: 2,
        },
      ],
      layers: [
        {
          id: 'alert-bg',
          name: 'Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-inner-glow',
          name: 'Inner Glow',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-accent-top',
          name: 'Accent Line Top',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-accent-bottom',
          name: 'Accent Line Bottom',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-icon',
          name: 'Icon/Avatar',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-title',
          name: 'Alert Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-message',
          name: 'Username/Message',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-subtitle',
          name: 'Subtitle',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['alert', 'notification', 'follower', 'subscriber', 'donation'],
      usage: 'Customize the colors, text, and icon to match your stream branding. Works for followers, subscribers, donations, raids, and more.',
    },
  },
];
